SET(VIRVO_VERSIONINFO_DIR
  ${CMAKE_CURRENT_BINARY_DIR}
)

SET(VIRVO_VERSIONINFO_H
  vvversioninfo.h
)

# Remember this for the make install target
SET(VIRVO_VERSIONINFO_ABS_H
  ${VIRVO_VERSIONINFO_DIR}/${VIRVO_VERSIONINFO_H}
  CACHE INTERNAL ""
)

IF(WIN32)
  ADD_CUSTOM_COMMAND(
    OUTPUT ${VIRVO_VERSIONINFO_ABS_H}
    COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/../makeversion.bat ${CMAKE_CURRENT_BINARY_DIR} 0
  )
ELSE(WIN32)
  ADD_CUSTOM_COMMAND(
    OUTPUT ${VIRVO_VERSIONINFO_ABS_H}
    COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/../makeversion.sh ${CMAKE_CURRENT_BINARY_DIR} 0
  )
ENDIF(WIN32)

INCLUDE_DIRECTORIES(${VIRVO_VERSIONINFO_DIR})
