# Generate autotools-like config header
FIND_PACKAGE(Cg)
IF(NOT ${CMAKE_VERSION} VERSION_LESS 2.8)
  FIND_PACKAGE(CUDA)
ENDIF(NOT ${CMAKE_VERSION} VERSION_LESS 2.8)
FIND_PACKAGE(GLEW REQUIRED)
FIND_PACKAGE(GLUT)
FIND_PACKAGE(Norm)
FIND_PACKAGE(OpenGL REQUIRED)
FIND_PACKAGE(X11)
FIND_PACKAGE(FFMPEG)
FIND_PACKAGE(SNAPPY)
FIND_PACKAGE(VolPack)

IF(CG_FOUND)
  SET(HAVE_CG 1)
  SET(HAVE_CG_CG_H 1)
ENDIF(CG_FOUND)

IF(CUDA_FOUND)
  SET(HAVE_CUDA 1) 
  SET(HAVE_CUDA_H 1)
ENDIF(CUDA_FOUND)

IF(NORM_FOUND)
  SET(HAVE_NORM 1)
  SET(HAVE_NORM_H 1)
ENDIF(NORM_FOUND)

IF(OPENGL_FOUND)
  SET(HAVE_GL 1)
ENDIF(OPENGL_FOUND)

IF(GLEW_FOUND)
  SET(HAVE_GLEW 1)
ENDIF(GLEW_FOUND)

IF(OPENGL_GLU_FOUND)
  SET(HAVE_GLU 1)
ENDIF(OPENGL_GLU_FOUND)

IF(GLUT_FOUND)
  SET(HAVE_GLUT 1)
ENDIF(GLUT_FOUND)

IF(X11_FOUND)
  SET(HAVE_X11_X_H 1)
ENDIF(X11_FOUND)

IF(FFMPEG_FOUND)
  SET(HAVE_FFMPEG 1)
ENDIF(FFMPEG_FOUND)

IF(SNAPPY_FOUND)
  SET(HAVE_SNAPPY 1)
ENDIF(SNAPPY_FOUND)

IF(VOLPACK_FOUND)
  SET(HAVE_VOLPACK 1)
ENDIF(VOLPACK_FOUND)

ADD_DEFINITIONS(-DHAVE_CONFIG_H)

SET(VIRVO_CONFIG_DIR
  ${CMAKE_CURRENT_BINARY_DIR}
)

SET(VIRVO_CONFIG_H
  vvconfig.h
)

CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/cmake/cmakeconfig.h.in ${VIRVO_CONFIG_DIR}/${VIRVO_CONFIG_H})
INCLUDE_DIRECTORIES(${VIRVO_CONFIG_DIR})
