macro(find_qt)
   set(SAVED_CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH})
   if(DESKVOX_USE_QT5)
      set(CMAKE_PREFIX_PATH $ENV{EXTERNLIBS}/qt5 ${CMAKE_PREFIX_PATH})
      find_package(Qt5Core REQUIRED)
      find_package(Qt5OpenGL REQUIRED)
      find_package(Qt5Gui REQUIRED)
      find_package(Qt5Gui REQUIRED)
      find_package(Qt5Widgets REQUIRED)
   else()
      set(CMAKE_PREFIX_PATH $ENV{EXTERNLIBS}/qt6 ${CMAKE_PREFIX_PATH})
      find_package(Qt6 COMPONENTS Core Gui Widgets OpenGL OpenGLWidgets Network Xml REQUIRED)
   endif()
   set(CMAKE_PREFIX_PATH ${SAVED_CMAKE_PREFIX_PATH})
endmacro(find_qt)

macro(qt_wrap_cpp)
   if(DESKVOX_USE_QT5)
      qt5_wrap_cpp(${ARGV})
   else()
      qt6_wrap_cpp(${ARGV})
   endif()
endmacro(qt_wrap_cpp)

macro(qt_wrap_ui)
    IF(DESKVOX_USE_QT5)
      qt5_wrap_ui(${ARGV})
   ELSE()
      qt6_wrap_ui(${ARGV})
   ENDIF()
endmacro(qt_wrap_ui)

macro(qt_add_resources)
    if(DESKVOX_USE_QT5)
      qt5_add_resources(${ARGV})
   else()
      qt6_add_resources(${ARGV})
   endif()
endmacro(qt_add_resources)

macro(qt_use_modules target)
    if(DESKVOX_USE_QT5)
      foreach(mod ${ARGN})
         if(${mod} STREQUAL Qt3Support)
            message("Qt 5 does not include Qt3Support")
            return()
         endif()
      endforeach()
      qt5_use_modules(${target} ${ARGN})
   else()
      foreach(mod ${ARGN})
         if(${mod} STREQUAL Qt3Support)
            message("Qt 6 does not include Qt3Support")
            return()
         endif()
      endforeach()
      qt6_use_modules(${target} ${ARGN})
   endif()
endmacro(qt_use_modules)
