macro(find_qt)

   set(REQUIRE)
   if(${ARGC} GREATER 0)
       set(REQUIRE ${ARG0})
   endif()
   
   set(SAVED_CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH})
   set(CMAKE_PREFIX_PATH $ENV{EXTERNLIBS}/qt ${CMAKE_PREFIX_PATH})
   if(NOT DESKVOX_USE_QT5)
      set(CMAKE_PREFIX_PATH $ENV{EXTERNLIBS}/qt6 ${CMAKE_PREFIX_PATH})
      find_package(Qt6 COMPONENTS Core Gui Widgets OpenGL OpenGLWidgets Network Xml ${REQUIRE})
      set(QT_FOUND ${Qt6_FOUND})
   endif()
   if(DESKVOX_USE_QT5 OR NOT ${QT_FOUND})
      set(CMAKE_PREFIX_PATH $ENV{EXTERNLIBS}/qt5 ${CMAKE_PREFIX_PATH})
      find_package(Qt5Core ${REQUIRE})
      find_package(Qt5OpenGL ${REQUIRE})
      find_package(Qt5Gui ${REQUIRE})
      find_package(Qt5Widgets ${REQUIRE})
      if(${Qt5Core_FOUND} AND ${Qt5OpenGL_FOUND} AND ${Qt5Gui_FOUND} AND ${Qt5Widgets_FOUND})
          set(QT_FOUND TRUE)
      endif()
   endif()
   set(CMAKE_PREFIX_PATH ${SAVED_CMAKE_PREFIX_PATH})
endmacro(find_qt)

macro(qt_wrap_cpp)
   if(DESKVOX_USE_QT5)
      qt5_wrap_cpp(${ARGV})
   else()
      qt6_wrap_cpp(${ARGV})
   endif()
endmacro(qt_wrap_cpp)

macro(qt_wrap_ui)
    IF(DESKVOX_USE_QT5)
      qt5_wrap_ui(${ARGV})
   ELSE()
      qt6_wrap_ui(${ARGV})
   ENDIF()
endmacro(qt_wrap_ui)

macro(qt_add_resources)
    if(DESKVOX_USE_QT5)
      qt5_add_resources(${ARGV})
   else()
      qt6_add_resources(${ARGV})
   endif()
endmacro(qt_add_resources)

macro(qt_use_modules target)
    if(DESKVOX_USE_QT5)
      qt5_use_modules(${target} ${ARGN})
   else()
      qt6_use_modules(${target} ${ARGN})
   endif()
endmacro(qt_use_modules)
