// Shader for 2D transfer functions.
// Author: 
//  Jurgen Schulze <schulze@cs.brown.edu>

struct PixelIn 
{
	float3 coord3d : TEXCOORD0;
};

float4 main(
 	const sampler3D  in uniform pix3dtex : TEXTURE0,
	const sampler2D  in uniform pixLUT,
	const PixelIn    in         IN) : COLOR0
{
	uniform float4 origColor = tex3D(pix3dtex, IN.coord3d);
	uniform float4 OUT = tex2D(pixLUT, float2(origColor.r, origColor.g));
	return OUT;
}
