// Authors: 
//  Martin Aumueller <aumueller@uni-koeln.de>

struct PixelIn 
{
	float3 tc0 : TEXCOORD0;
	float3 tc1 : TEXCOORD1;
};

float4 main(
 	const sampler3D  in uniform pix3dtex : TEXTURE0,
	const sampler2D  in uniform pixLUT,
	      PixelIn    in         IN) : COLOR0
{
	float r = tex3D(pix3dtex, IN.tc0).r;
	float g = tex3D(pix3dtex, IN.tc1).g;
	float4 OUT = tex2D(pixLUT, float2(g, r));
        return OUT;
}
